name: Build Beamer Presentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install minimal TeX Live packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-latex-extra

      - name: Compile Beamer Presentation
        run: |
          pdflatex -output-directory=output presentation/prezentace.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: beamer-presentation
          path: presentation/prezentace.pdf