name: Build Beamer Presentation

on:
  push:
    branches:
      - main
    paths:
      - 'presentation/prezentace.tex'
  pull_request:
    branches:
      - main
    paths:
      - 'presentation/prezentace.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install minimal TeX Live packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-latex-extra \
            texlive-lang-czechslovak

      - name: Clean previous build files
        run: rm -f presentation/*.pdf presentation/*.aux presentation/*.log

      - name: Compile Beamer Presentation
        run: |
          pdflatex -output-directory=presentation presentation/prezentace.tex
          pdflatex -output-directory=presentation presentation/prezentace.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: beamer-presentation
          path: presentation/prezentace.pdf

      - name: Create Release (only on push to main)
        if: github.ref == 'refs/heads/main'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v$(date +'%Y%m%d-%H%M%S')"
          release_name: "Beamer Presentation $(date +'%Y-%m-%d %H:%M:%S')"
          draft: false
          prerelease: false

      - name: Upload PDF to Release
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: presentation/prezentace.pdf
          asset_name: prezentace.pdf
          asset_content_type: application/pdf

      - name: Post PR Comment with Artifact Link (only on pull request)
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :page_facing_up: The generated PDF presentation is available as an artifact.
            [Download PDF](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts)